export const content = {
  fa: {
    title: "فرم تماس",
    subtitle: "برای ارتباط با ما فرم زیر را تکمیل کنید",
    fields: {
      name: "نام و نام خانوادگی",
      email: "ایمیل",
      phone: "تلفن (اختیاری)",
      company: "نام شرکت (اختیاری)",
      subject: "موضوع",
      message: "پیام",
      preferredContact: "روش ارتباط ترجیحی",
      consent: "سیاست حفظ حریم خصوصی را می‌پذیرم",
    },
    contactMethods: {
      email: "ایمیل",
      phone: "تلفن",
    },
    placeholders: {
      name: "نام خود را وارد کنید",
      email: "example@email.com",
      phone: "+98 912 345 6789",
      company: "نام شرکت خود را وارد کنید",
      subject: "موضوع پیام خود را بنویسید",
      message: "پیام خود را اینجا بنویسید...",
    },
    submit: "ارسال پیام",
    submitting: "در حال ارسال...",
    success: "پیام شما با موفقیت ارسال شد!",
    successMessage: "ما در اسرع وقت با شما تماس خواهیم گرفت.",
    error: "خطا در ارسال پیام",
    errorMessage: "لطفاً دوباره تلاش کنید یا با ما تماس بگیرید.",
    validation: {
      nameMin: "نام باید حداقل ۲ کاراکتر باشد",
      nameMax: "نام نباید بیشتر از ۱۰۰ کاراکتر باشد",
      emailRequired: "ایمیل الزامی است",
      emailInvalid: "ایمیل معتبر نیست",
      emailMax: "ایمیل نباید بیشتر از ۲۵۴ کاراکتر باشد",
      phoneInvalid: "شماره تلفن معتبر نیست",
      phoneMax: "شماره تلفن نباید بیشتر از ۵۰ کاراکتر باشد",
      companyMax: "نام شرکت نباید بیشتر از ۱۰۰ کاراکتر باشد",
      subjectMin: "موضوع باید حداقل ۳ کاراکتر باشد",
      subjectMax: "موضوع نباید بیشتر از ۲۰۰ کاراکتر باشد",
      messageMin: "پیام باید حداقل ۱۰ کاراکتر باشد",
      messageMax: "پیام نباید بیشتر از ۲۰۰۰ کاراکتر باشد",
      consentRequired: "باید سیاست حفظ حریم خصوصی را بپذیرید",
    },
  },
  en: {
    title: "Contact Form",
    subtitle: "Fill out the form below to get in touch with us",
    fields: {
      name: "Full Name",
      email: "Email",
      phone: "Phone (Optional)",
      company: "Company Name (Optional)",
      subject: "Subject",
      message: "Message",
      preferredContact: "Preferred Contact Method",
      consent: "I accept the privacy policy",
    },
    contactMethods: {
      email: "Email",
      phone: "Phone",
    },
    placeholders: {
      name: "Enter your name",
      email: "example@email.com",
      phone: "+98 912 345 6789",
      company: "Enter your company name",
      subject: "Enter your message subject",
      message: "Write your message here...",
    },
    submit: "Send Message",
    submitting: "Sending...",
    success: "Your message has been sent successfully!",
    successMessage: "We will get back to you as soon as possible.",
    error: "Error sending message",
    errorMessage: "Please try again or contact us directly.",
    validation: {
      nameMin: "Name must be at least 2 characters",
      nameMax: "Name must be at most 100 characters",
      emailRequired: "Email is required",
      emailInvalid: "Invalid email address",
      emailMax: "Email must be at most 254 characters",
      phoneInvalid: "Invalid phone number",
      phoneMax: "Phone number must be at most 50 characters",
      companyMax: "Company name must be at most 100 characters",
      subjectMin: "Subject must be at least 3 characters",
      subjectMax: "Subject must be at most 200 characters",
      messageMin: "Message must be at least 10 characters",
      messageMax: "Message must be at most 2000 characters",
      consentRequired: "You must accept the privacy policy",
    },
  },
};

export type ContactContent = typeof content.en;
export type ContentValidation = ContactContent['validation'];
